import { execSync, type ExecSyncOptionsWithStringEncoding } from 'child_process';
import type { FixLogger } from './logger';
import type { FixPlan } from './plan-types';

const EXEC_OPTS: ExecSyncOptionsWithStringEncoding = { encoding: 'utf-8', timeout: 120_000 };

const GITHUB_API = 'https://api.github.com';

interface PRResult {
  prUrl: string;
  prNumber: number;
  prBranch: string;
  prRepoFullName: string;
  diffSummary: string;
}

function commitMessage(plan: FixPlan): string {
  const finding = `${plan.finding.type}/${plan.finding.id}`;
  return `fix(security): ${plan.summary}\n\nResolves ${finding}.\n\nGenerated by Aegis Fix Agent.`;
}

function branchName(fixId: string, plan: FixPlan): string {
  const finding = plan.finding.id.toLowerCase().replace(/[^a-z0-9-]/g, '-').slice(0, 40);
  return `aegis/fix-${finding}-${fixId.slice(0, 8)}`;
}

function buildPRBody(plan: FixPlan, diffSummary: string): string {
  const lines: string[] = [];
  lines.push(`## ${plan.summary}`);
  lines.push('');
  lines.push(`**Finding:** \`${plan.finding.type}/${plan.finding.id}\``);
  if (plan.finding.severity) lines.push(`**Severity:** ${plan.finding.severity}`);
  lines.push('');
  lines.push('### Current state');
  for (const b of plan.currentState) lines.push(`- ${b}`);
  lines.push('');
  lines.push('### Desired state');
  for (const b of plan.desiredState) lines.push(`- ${b}`);
  lines.push('');
  lines.push('### Test command');
  lines.push('```');
  lines.push(plan.testCommand);
  lines.push('```');
  if (diffSummary) {
    lines.push('');
    lines.push('### Diff summary');
    lines.push('```');
    lines.push(diffSummary);
    lines.push('```');
  }
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [Aegis Fix Agent](https://deptex.dev). Review carefully before merging.*');
  return lines.join('\n');
}

export async function commitAndPushFix(opts: {
  workDir: string;
  fixId: string;
  plan: FixPlan;
  installationToken: string;
  repoFullName: string;
  baseBranch: string;
  logger: FixLogger;
}): Promise<{ prBranch: string; diffSummary: string }> {
  const { workDir, fixId, plan, installationToken, repoFullName, baseBranch, logger } = opts;

  // Configure committer identity for this repo only.
  execSync('git config user.email "aegis@deptex.dev"', { ...EXEC_OPTS, cwd: workDir });
  execSync('git config user.name "Aegis Fix Agent"', { ...EXEC_OPTS, cwd: workDir });

  const branch = branchName(fixId, plan);
  await logger.info('pr', `Creating branch ${branch}`);
  execSync(`git checkout -b "${branch}"`, { ...EXEC_OPTS, cwd: workDir });
  execSync('git add -A', { ...EXEC_OPTS, cwd: workDir });

  const stat = execSync('git diff --cached --stat', { ...EXEC_OPTS, cwd: workDir }).trim();
  if (!stat) {
    // Diagnostic: dump unstaged status + working-tree listing so we can tell
    // whether the patches landed in unexpected places, were silently no-ops,
    // or got swallowed by .gitignore.
    const porcelain = execSync('git status --porcelain --ignored', { ...EXEC_OPTS, cwd: workDir }).trim();
    const tree = execSync('ls -la', { ...EXEC_OPTS, cwd: workDir }).trim();
    throw new Error(
      `No changes to commit — editor produced an empty diff. git status: "${porcelain}" | top-level: "${tree.slice(0, 600)}"`,
    );
  }

  const message = commitMessage(plan);
  // Pass the message via stdin to avoid shell-escaping pitfalls.
  execSync(`git commit -F -`, {
    ...EXEC_OPTS,
    cwd: workDir,
    input: message,
  });

  await logger.info('pr', 'Pushing branch');
  const remoteUrl = `https://x-access-token:${installationToken}@github.com/${repoFullName}.git`;
  execSync(`git remote set-url origin "${remoteUrl}"`, { ...EXEC_OPTS, cwd: workDir });
  execSync(`git push --set-upstream origin "${branch}"`, {
    ...EXEC_OPTS,
    cwd: workDir,
    timeout: 120_000,
  });

  // Belt-and-braces: clear the token from origin so it isn't kept in .git/config.
  execSync(`git remote set-url origin "https://github.com/${repoFullName}.git"`, {
    ...EXEC_OPTS,
    cwd: workDir,
  });

  return { prBranch: branch, diffSummary: stat };
}

export async function openPullRequest(opts: {
  installationToken: string;
  repoFullName: string;
  branch: string;
  baseBranch: string;
  plan: FixPlan;
  diffSummary: string;
  logger: FixLogger;
}): Promise<PRResult> {
  const { installationToken, repoFullName, branch, baseBranch, plan, diffSummary, logger } = opts;
  await logger.info('pr', 'Opening pull request');

  const res = await fetch(`${GITHUB_API}/repos/${repoFullName}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${installationToken}`,
      Accept: 'application/vnd.github+json',
      'User-Agent': 'Deptex-Aegis-Fix',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      title: `Fix: ${plan.summary}`,
      head: branch,
      base: baseBranch,
      body: buildPRBody(plan, diffSummary),
      draft: true,
    }),
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub PR creation failed: ${res.status} ${text}`);
  }
  const pr = (await res.json()) as { html_url: string; number: number };
  await logger.success('pr', `PR opened: ${pr.html_url}`);

  return {
    prUrl: pr.html_url,
    prNumber: pr.number,
    prBranch: branch,
    prRepoFullName: repoFullName,
    diffSummary,
  };
}
