apiVersion: apps/v1
kind: Deployment
metadata:
  name: deptex-dogfood-aspnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deptex-dogfood-aspnet
  template:
    metadata:
      labels:
        app: deptex-dogfood-aspnet
    spec:
      containers:
        - name: app
          image: deptex-dogfood-aspnet:latest
          ports:
            - containerPort: 4011
          securityContext:
            # CKV_K8S_16
            privileged: true
            # CKV_K8S_20
            runAsNonRoot: false
            # CKV_K8S_22
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        # CKV_K8S_8
        - name: host-root
          hostPath:
            path: /
