/**
 * Phase 17: Post-mortem generation.
 *
 * Strategy: Markdown-first with optional AI enhancement.
 * Server generates structured markdown from incident data + timeline.
 * Optional BYOK AI can enhance "Root Cause" and "Recommendations".
 * Frontend provides PDF export via window.print().
 */

import { supabase } from '../../../backend/src/lib/supabase';

export async function generatePostMortem(incidentId: string): Promise<string> {
  const incident = await loadIncidentWithTimeline(incidentId);
  if (!incident) throw new Error('Incident not found');

  let markdown = buildTemplatePostMortem(incident);

  try {
    const { getProviderForOrg } = require('./ai/provider');
    const provider = await getProviderForOrg(incident.organization_id);
    if (provider) {
      const enhanced = await enhanceWithAI(provider, markdown, incident);
      if (enhanced) markdown = enhanced;
    }
  } catch {
    // AI enhancement failed — template version is fine
  }

  await supabase
    .from('security_incidents')
    .update({ post_mortem: markdown })
    .eq('id', incidentId);

  return markdown;
}

async function loadIncidentWithTimeline(incidentId: string) {
  const { data: incident } = await supabase
    .from('security_incidents')
    .select('*')
    .eq('id', incidentId)
    .single();

  if (!incident) return null;

  const { data: timeline } = await supabase
    .from('incident_timeline')
    .select('*')
    .eq('incident_id', incidentId)
    .order('created_at', { ascending: true });

  const { data: notes } = await supabase
    .from('incident_notes')
    .select('*')
    .eq('incident_id', incidentId)
    .order('created_at', { ascending: true });

  return { ...incident, timeline: timeline || [], notes: notes || [] };
}

function buildTemplatePostMortem(incident: any): string {
  const lines: string[] = [];

  lines.push(`# Security Incident Report: ${incident.title}`);
  lines.push('');
  lines.push('## Summary');
  lines.push(`- **Type**: ${formatIncidentType(incident.incident_type)}`);
  lines.push(`- **Severity**: ${incident.severity}`);
  lines.push(`- **Declared**: ${formatDate(incident.declared_at)}`);
  lines.push(`- **Resolved**: ${incident.resolved_at ? formatDate(incident.resolved_at) : 'Pending'}`);
  lines.push(`- **Duration**: ${formatDuration(incident.total_duration_ms)}`);
  if (incident.is_false_positive) {
    lines.push('- **Classification**: False Positive');
  }
  lines.push('');

  lines.push('## Impact');
  const projectCount = incident.affected_projects?.length || 0;
  lines.push(`- **Affected Projects**: ${projectCount}`);
  if (incident.affected_packages?.length) {
    lines.push(`- **Affected Packages**: ${incident.affected_packages.join(', ')}`);
  }
  if (incident.affected_cves?.length) {
    lines.push(`- **Vulnerabilities**: ${incident.affected_cves.join(', ')}`);
  }
  lines.push('');

  lines.push('## Timeline');
  lines.push('');
  lines.push('| Time | Phase | Action |');
  lines.push('|------|-------|--------|');
  for (const event of incident.timeline) {
    const time = formatDate(event.created_at);
    const phase = event.phase;
    const desc = event.description.replace(/\|/g, '\\|');
    lines.push(`| ${time} | ${phase} | ${desc} |`);
  }
  lines.push('');

  lines.push('## Metrics');
  lines.push(`- **Time to Contain**: ${formatDuration(incident.time_to_contain_ms)}`);
  lines.push(`- **Time to Remediate**: ${formatDuration(incident.time_to_remediate_ms)}`);
  lines.push(`- **Fixes Created**: ${incident.fixes_created || 0}`);
  lines.push(`- **PRs Merged**: ${incident.prs_merged || 0}`);
  if (incident.escalation_level > 0) {
    lines.push(`- **Escalation Level**: ${incident.escalation_level}`);
  }
  lines.push('');

  if (incident.autonomous_actions_taken?.length > 0) {
    lines.push('## Autonomous Actions');
    lines.push('');
    for (const action of incident.autonomous_actions_taken) {
      lines.push(`- ${typeof action === 'string' ? action : JSON.stringify(action)}`);
    }
    lines.push('');
  }

  if (incident.notes?.length > 0) {
    lines.push('## Notes');
    lines.push('');
    for (const note of incident.notes) {
      lines.push(`> **${formatDate(note.created_at)}**: ${note.content}`);
    }
    lines.push('');
  }

  lines.push('## Root Cause');
  lines.push('');
  lines.push('See incident timeline for details.');
  lines.push('');

  lines.push('## Recommendations');
  lines.push('');
  lines.push('Review incident timeline and affected scope for preventive measures.');
  lines.push('');

  lines.push('---');
  lines.push(`*Generated by Deptex Incident Response on ${formatDate(new Date().toISOString())}*`);

  return lines.join('\n');
}

async function enhanceWithAI(
  provider: any,
  templateMarkdown: string,
  incident: any,
): Promise<string | null> {
  try {
    const prompt = `You are a security incident report specialist. Enhance this incident post-mortem report by adding a detailed "Root Cause" analysis and specific "Recommendations" section. Use only the data provided — do not fabricate CVE details or package names.

Incident Summary:
- Type: ${incident.incident_type}
- Severity: ${incident.severity}
- Affected Packages: ${(incident.affected_packages || []).join(', ') || 'none listed'}
- Affected CVEs: ${(incident.affected_cves || []).join(', ') || 'none listed'}
- Projects: ${incident.affected_projects?.length || 0}
- Duration: ${formatDuration(incident.total_duration_ms)}
- Time to Contain: ${formatDuration(incident.time_to_contain_ms)}
- Timeline Events: ${incident.timeline?.length || 0}
- Escalations: ${incident.escalation_level || 0}

Current report:
${templateMarkdown}

Replace the "Root Cause" and "Recommendations" sections with substantive analysis. Return the full markdown document.`;

    const result = await provider.chat([
      { role: 'system', content: 'You are a security incident report specialist for Deptex, a dependency security platform.' },
      { role: 'user', content: prompt },
    ]);

    if (result?.content && result.content.length > templateMarkdown.length * 0.5) {
      return result.content;
    }
  } catch (err: any) {
    console.error('[incident-postmortem] AI enhancement failed:', err.message);
  }
  return null;
}

function formatIncidentType(type: string): string {
  const labels: Record<string, string> = {
    zero_day: 'Zero-Day CVE',
    supply_chain: 'Supply Chain Compromise',
    secret_exposure: 'Secret Exposure',
    compliance_breach: 'Compliance Breach',
    custom: 'Custom',
  };
  return labels[type] || type;
}

function formatDate(dateStr: string | null): string {
  if (!dateStr) return 'N/A';
  return new Date(dateStr).toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  });
}

function formatDuration(ms: number | null | undefined): string {
  if (!ms || ms <= 0) return 'N/A';
  const totalSec = Math.floor(ms / 1000);
  if (totalSec < 60) return `${totalSec}s`;
  const min = Math.floor(totalSec / 60);
  if (min < 60) return `${min}m`;
  const hours = Math.floor(min / 60);
  const remainMin = min % 60;
  if (hours < 24) return `${hours}h ${remainMin}m`;
  const days = Math.floor(hours / 24);
  return `${days}d ${hours % 24}h`;
}
