/**
 * Dumps the live Supabase public schema to backend/database/schema.sql.
 *
 * Used by: (1) local depscanner PGLite backend, (2) CI smoke tests.
 * Run: `npm run schema:dump` (from backend/depscanner/).
 *
 * Rule (see CLAUDE.md): if you add/modify a file in backend/database/*.sql,
 * run this script in the same PR so schema.sql stays in sync. The CI check at
 * .github/workflows/schema-check.yml enforces this.
 *
 * Calls the pg_catalog_dump_v1_all() JSONB wrapper installed by
 * backend/database/phase26_6_schema_dump_jsonb.sql, which sits on top of
 * pg_catalog_dump_v1() (phase19_4_schema_dump_helper.sql). The JSONB
 * wrapper exists so the dump bypasses PostgREST's db-max-rows cap (1000
 * on managed Supabase) — the schema crossed 1000 rows during Phase 6 and
 * silently truncated the trigger section without it.
 */

import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const OUT_FILE = path.resolve(__dirname, '../../database/schema.sql');

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in backend/.env');
  process.exit(1);
}

const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

interface DumpRow {
  kind: string;
  ord: number;
  ddl: string;
}

async function main() {
  console.log('Dumping schema from', SUPABASE_URL);

  const { data, error } = await sb.rpc('pg_catalog_dump_v1_all');
  if (error) {
    console.error('pg_catalog_dump_v1_all() call failed:', error.message);
    console.error(
      '\nIf the function is missing, apply both migrations:\n' +
        '  backend/database/phase19_4_schema_dump_helper.sql\n' +
        '  backend/database/phase26_6_schema_dump_jsonb.sql\n' +
        'via the Supabase SQL editor, then re-run this script.',
    );
    process.exit(1);
  }

  // JSONB wrapper already sorts by (ord, ddl); copy out so the type-asserted
  // array is mutable for any downstream tweaks.
  const rows = ((data as DumpRow[] | null) ?? []).slice();

  const out: string[] = [];
  out.push('-- Deptex schema dump');
  out.push('-- Generated by backend/depscanner/scripts/dump-schema.ts');
  out.push('-- Single source of truth for local-mode depscanner (PGLite backend).');
  out.push('-- Regenerate via `npm run schema:dump` whenever a migration lands in main.');
  out.push('--');
  out.push('-- RLS ENABLE statements are intentionally excluded — local mode runs without');
  out.push('-- auth and RLS-enabled tables without policies would return empty on SELECT.');
  out.push('');
  out.push('-- ============================================');
  out.push('-- EXTENSIONS');
  out.push('-- ============================================');
  out.push('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";');
  out.push('CREATE EXTENSION IF NOT EXISTS vector;');
  out.push('');

  const sections: Record<string, string> = {
    enum: 'ENUM TYPES',
    table: 'TABLES',
    constraint: 'CONSTRAINTS (PK, UNIQUE, CHECK, FK — in that order)',
    index: 'INDEXES',
    function: 'FUNCTIONS',
    trigger: 'TRIGGERS',
  };

  let currentKind = '';
  for (const row of rows) {
    if (row.kind !== currentKind) {
      out.push('');
      out.push('-- ============================================');
      out.push('-- ' + (sections[row.kind] ?? row.kind.toUpperCase()));
      out.push('-- ============================================');
      currentKind = row.kind;
    }
    out.push(row.ddl);
    if (row.kind === 'function') out.push('');
  }

  fs.writeFileSync(OUT_FILE, out.join('\n') + '\n');
  const sizeKb = (fs.statSync(OUT_FILE).size / 1024).toFixed(1);
  const counts: Record<string, number> = {};
  for (const r of rows) counts[r.kind] = (counts[r.kind] ?? 0) + 1;
  console.log(`\nWrote ${OUT_FILE} (${sizeKb} KB)`);
  for (const [k, v] of Object.entries(counts).sort()) {
    console.log(`  ${k}s: ${v}`);
  }
}

main().catch((e) => {
  console.error('dump-schema failed:', e);
  process.exit(1);
});
