-- Phase 19.4: Schema dump helper
--
-- Single SQL function called by backend/extraction-worker/scripts/dump-schema.ts
-- to regenerate backend/database/schema.sql from live Supabase.
--
-- Returns DDL for: enums, tables, constraints, indexes, functions, triggers (public schema).
-- SECURITY DEFINER = only service_role needs access (RLS bypass through pg_catalog).

CREATE OR REPLACE FUNCTION pg_catalog_dump_v1()
RETURNS TABLE(kind text, ord int, ddl text)
LANGUAGE sql
SECURITY DEFINER
AS $fn$
  -- ENUMS
  SELECT 'enum'::text AS kind, 10 AS ord,
    'CREATE TYPE ' || n.nspname || '.' || t.typname || ' AS ENUM (' ||
    string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) || ');' AS ddl
  FROM pg_type t
  JOIN pg_enum e ON e.enumtypid = t.oid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
  GROUP BY n.nspname, t.typname

  UNION ALL

  -- TABLES (CREATE TABLE IF NOT EXISTS ... with columns inline, no constraints)
  SELECT 'table'::text, 20,
    'CREATE TABLE IF NOT EXISTS public.' || quote_ident(c.table_name) || E' (\n' ||
    string_agg('  ' || quote_ident(c.column_name) || ' ' ||
      CASE
        WHEN c.data_type = 'USER-DEFINED' THEN c.udt_schema || '.' || c.udt_name
        WHEN c.data_type = 'ARRAY' THEN
          CASE WHEN c.udt_name LIKE E'\\_%' THEN substring(c.udt_name, 2) || '[]' ELSE c.udt_name END
        WHEN c.data_type = 'character varying' AND c.character_maximum_length IS NOT NULL
          THEN 'varchar(' || c.character_maximum_length || ')'
        WHEN c.data_type = 'numeric' AND c.numeric_precision IS NOT NULL
          THEN 'numeric(' || c.numeric_precision || COALESCE(',' || c.numeric_scale, '') || ')'
        ELSE c.data_type
      END ||
      CASE WHEN c.is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END ||
      COALESCE(' DEFAULT ' || c.column_default, ''),
      E',\n' ORDER BY c.ordinal_position) || E'\n);' AS ddl
  FROM information_schema.columns c
  WHERE c.table_schema = 'public'
  GROUP BY c.table_name

  UNION ALL

  -- CONSTRAINTS (ordered PK -> UNIQUE -> CHECK -> FK so refs resolve)
  SELECT 'constraint'::text,
    30 + CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2 WHEN 'f' THEN 3 ELSE 9 END,
    'ALTER TABLE public.' || quote_ident(con.conrelid::regclass::text) ||
    ' ADD CONSTRAINT ' || quote_ident(con.conname) || ' ' ||
    pg_get_constraintdef(con.oid) || ';'
  FROM pg_constraint con
  JOIN pg_namespace n ON n.oid = con.connamespace
  WHERE n.nspname = 'public'

  UNION ALL

  -- INDEXES (excluding ones auto-generated by PK/UNIQUE)
  SELECT 'index'::text, 40, indexdef || ';'
  FROM pg_indexes
  WHERE schemaname = 'public'
    AND indexname NOT IN (
      SELECT conname FROM pg_constraint c2
      JOIN pg_namespace n2 ON n2.oid = c2.connamespace
      WHERE n2.nspname = 'public' AND c2.contype IN ('p', 'u')
    )

  UNION ALL

  -- FUNCTIONS
  SELECT 'function'::text, 50, pg_get_functiondef(p.oid) || ';'
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.prokind = 'f'

  UNION ALL

  -- TRIGGERS (user-defined only)
  SELECT 'trigger'::text, 60, pg_get_triggerdef(t.oid) || ';'
  FROM pg_trigger t
  JOIN pg_class c ON c.oid = t.tgrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public' AND NOT t.tgisinternal;
$fn$;

COMMENT ON FUNCTION pg_catalog_dump_v1() IS
  'Phase 19.4: emits DDL for public schema. Used by backend/extraction-worker/scripts/dump-schema.ts to regenerate backend/database/schema.sql for PGLite local-mode. Do not drop.';
