-- Phase 5: Seed license_obligations from spdx-obligations.json
-- Run after phase5_license_obligations.sql
-- Note: Full license texts are not included in this seed. Packages using licenses
-- not in this table will have their license name shown without full text in the legal notice.

INSERT INTO license_obligations (license_spdx_id, requires_attribution, requires_notice_file, requires_source_disclosure, requires_license_text, is_copyleft, is_weak_copyleft, summary)
VALUES
  ('MIT', true, false, false, true, false, false, 'Requires copyright notice and license text in distributions. Very permissive.'),
  ('Apache-2.0', true, true, false, true, false, false, 'Requires copyright notice, NOTICE file, and license text. Includes patent grant.'),
  ('BSD-2-Clause', true, false, false, true, false, false, 'Requires copyright notice and license text. Simplified BSD.'),
  ('BSD-3-Clause', true, false, false, true, false, false, 'Requires copyright notice and license text. No endorsement clause.'),
  ('ISC', true, false, false, true, false, false, 'Requires copyright notice and license text. Functionally equivalent to MIT.'),
  ('0BSD', false, false, false, false, false, false, 'No requirements. Public-domain-equivalent BSD license.'),
  ('Unlicense', false, false, false, false, false, false, 'No requirements. Dedicates work to the public domain.'),
  ('CC0-1.0', false, false, false, false, false, false, 'No requirements. Creative Commons public domain dedication.'),
  ('CC-BY-4.0', true, false, false, true, false, false, 'Requires attribution and license reference. Creative Commons Attribution.'),
  ('CC-BY-SA-4.0', true, false, false, true, true, false, 'Requires attribution and share-alike (copyleft). Creative Commons Attribution-ShareAlike.'),
  ('MPL-2.0', true, false, true, true, false, true, 'File-level copyleft: modified files must remain MPL-2.0. New files can use any license.'),
  ('LGPL-2.1-only', true, false, true, true, false, true, 'Weak copyleft: modifications to the library must be disclosed. Linking is permitted.'),
  ('LGPL-2.1-or-later', true, false, true, true, false, true, 'Weak copyleft: modifications to the library must be disclosed. Linking is permitted.'),
  ('LGPL-3.0-only', true, false, true, true, false, true, 'Weak copyleft: modifications to the library must be disclosed. Linking is permitted.'),
  ('LGPL-3.0-or-later', true, false, true, true, false, true, 'Weak copyleft: modifications to the library must be disclosed. Linking is permitted.'),
  ('GPL-2.0-only', true, false, true, true, true, false, 'Strong copyleft: all derivative works must be GPL-2.0. Source disclosure required.'),
  ('GPL-2.0-or-later', true, false, true, true, true, false, 'Strong copyleft: all derivative works must be GPL-2.0+. Source disclosure required.'),
  ('GPL-3.0-only', true, false, true, true, true, false, 'Strong copyleft: all derivative works must be GPL-3.0. Source disclosure required. Anti-tivoization.'),
  ('GPL-3.0-or-later', true, false, true, true, true, false, 'Strong copyleft: all derivative works must be GPL-3.0+. Source disclosure required.'),
  ('AGPL-3.0-only', true, false, true, true, true, false, 'Network copyleft: source must be available to users interacting over a network. Strongest copyleft.'),
  ('AGPL-3.0-or-later', true, false, true, true, true, false, 'Network copyleft: source must be available to users interacting over a network.'),
  ('EPL-1.0', true, false, true, true, false, true, 'Weak copyleft: modifications to EPL files must be disclosed. Compatible with commercial use.'),
  ('EPL-2.0', true, false, true, true, false, true, 'Weak copyleft: modifications to EPL files must be disclosed. Secondary license option.'),
  ('CDDL-1.0', true, false, true, true, false, true, 'File-level copyleft similar to MPL. Not GPL-compatible.'),
  ('CDDL-1.1', true, false, true, true, false, true, 'File-level copyleft similar to MPL. Not GPL-compatible.'),
  ('EUPL-1.2', true, false, true, true, true, false, 'EU copyleft license. Compatible with GPL, LGPL, MPL, AGPL, and others.'),
  ('Artistic-2.0', true, false, false, true, false, false, 'Requires attribution and license text. Used primarily by Perl ecosystem.'),
  ('Zlib', true, false, false, false, false, false, 'Requires copyright notice in source. No requirements for binary distributions.'),
  ('BSL-1.0', true, false, false, true, false, false, 'Requires copyright notice in source. Very permissive. Used by Boost libraries.'),
  ('WTFPL', false, false, false, false, false, false, 'No requirements. Do What The F*** You Want To Public License.'),
  ('PostgreSQL', true, false, false, true, false, false, 'Requires copyright notice. Very permissive, similar to BSD/MIT.'),
  ('PSF-2.0', true, false, false, true, false, false, 'Python Software Foundation license. Permissive, requires attribution.'),
  ('Python-2.0', true, false, false, true, false, false, 'Python 2.0 license. Permissive, requires attribution.'),
  ('Ruby', true, false, false, true, false, false, 'Ruby license. Dual-licensed with BSD-2-Clause.'),
  ('BlueOak-1.0.0', true, false, false, false, false, false, 'Modern permissive license. Requires attribution. Includes patent grant.'),
  ('MS-PL', true, false, false, true, false, false, 'Microsoft Public License. Permissive, requires license text.'),
  ('MS-RL', true, false, true, true, false, true, 'Microsoft Reciprocal License. File-level copyleft for modified files.'),
  ('CECILL-2.1', true, false, true, true, true, false, 'French copyleft license. Compatible with GPL. Requires source disclosure.'),
  ('OSL-3.0', true, false, true, true, true, false, 'Open Software License. Copyleft with network use trigger similar to AGPL.'),
  ('AFL-3.0', true, false, false, true, false, false, 'Academic Free License. Permissive with patent grant.'),
  ('NCSA', true, false, false, true, false, false, 'UIUC/NCSA license. Combines MIT and BSD-3 terms.'),
  ('Unicode-DFS-2016', true, false, false, true, false, false, 'Unicode data files license. Permissive, requires copyright notice.'),
  ('OFL-1.1', true, false, false, true, false, false, 'SIL Open Font License. Fonts must include license. Cannot sell fonts alone.'),
  ('X11', true, false, false, true, false, false, 'X11 license. Nearly identical to MIT. Requires copyright notice.'),
  ('Vim', true, false, false, true, false, false, 'Vim license. Charityware, permissive with attribution requirement.'),
  ('curl', true, false, false, true, false, false, 'curl license. MIT-style, requires copyright notice.'),
  ('IJG', true, false, false, false, false, false, 'Independent JPEG Group license. Permissive, requires acknowledgement.'),
  ('OpenSSL', true, false, false, true, false, false, 'OpenSSL license. Dual Apache/BSD-style. Requires attribution in advertising.'),
  ('SSPL-1.0', true, false, true, true, true, false, 'Server Side Public License. Strong copyleft: must disclose source of service infrastructure.'),
  ('BUSL-1.1', true, false, false, true, false, false, 'Business Source License. Source-available, converts to open-source after change date.')
ON CONFLICT (license_spdx_id) DO NOTHING;
